# Generated by Django 5.1.4 on 2025-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.IntegerField(unique=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("total_amount", models.FloatField()),
                ("date", models.DateField()),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("not_paid", "Not Paid"), ("paid", "Paid")],
                        max_length=50,
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("packed", "Packed"),
                            ("delivered", "Delivered"),
                            ("shipped", "Shipped"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("supplier", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_no", models.IntegerField(unique=True)),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("supplier_name", models.CharField(max_length=100)),
                ("contact", models.IntegerField(blank=True, null=True)),
                ("total_amount", models.FloatField()),
                ("date", models.DateField()),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_received", "Not Received"),
                            ("received", "Received"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=100)),
                ("contact", models.IntegerField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
