# Generated by Django 5.1.4 on 2025-01-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0003_orders_user_purchaseorder_user_supplier_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="contact",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
