# Generated by Django 5.1.4 on 2025-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0004_alter_supplier_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="invApp.product"),
        ),
    ]
