# Generated by Django 5.1.4 on 2025-01-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0006_orders_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="quantity",
        ),
    ]
