# Generated by Django 5.1.4 on 2025-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0007_remove_orders_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="total_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
