# Generated by Django 5.1.4 on 2025-01-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0008_orders_total_cost_product_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="total_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="contact",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
