# Generated by Django 5.1.4 on 2025-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0009_alter_orders_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="number_of_products",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
