# Generated by Django 5.1.4 on 2025-01-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0010_orders_number_of_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
