# Generated by Django 5.1.4 on 2025-01-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0011_product_cost_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="products",
            field=models.ManyToManyField(
                related_name="purchaseorder", to="invApp.product"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invApp.supplier"
            ),
        ),
    ]
