# Generated by Django 5.1.4 on 2025-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0012_purchaseorder_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[("not_received", "Not Received"), ("received", "Received")],
                default="not_received",
                max_length=50,
            ),
        ),
    ]
