# Generated by Django 5.1.4 on 2025-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0014_alter_purchaseorder_supplier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="contact",
            field=models.CharField(max_length=50),
        ),
    ]
