# Generated by Django 5.1.4 on 2025-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0015_alter_purchaseorder_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="products",
        ),
    ]
