# Generated by Django 5.1.4 on 2025-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0016_remove_purchaseorder_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="description",
            new_name="supplies",
        ),
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ManyToManyField(related_name="product", to="invApp.supplier"),
        ),
    ]
