# Generated by Django 5.1.4 on 2025-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0018_remove_product_supplier_product_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="units_sold",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
