# Generated by Django 5.1.4 on 2025-01-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0019_product_units_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="units_sold",
            field=models.IntegerField(default=0),
        ),
    ]
