# Generated by Django 5.1.4 on 2025-01-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0020_alter_product_units_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="delivery",
            field=models.CharField(
                choices=[
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="packed",
                max_length=50,
            ),
        ),
    ]
